name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build and Package on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable
      - name: Build
        run: cargo build --release
      - name: Package binary
        run: |
          mkdir -p dist
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            cp target/release/journaler.exe dist/journaler-${{ matrix.os }}.exe
          else
            cp target/release/journaler dist/journaler-${{ matrix.os }}
          fi
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: journaler-${{ matrix.os }}
          path: dist/*
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: journaler-ubuntu-latest
          path: dist/
      - uses: actions/download-artifact@v4
        with:
          name: journaler-macos-latest
          path: dist/
      - uses: actions/download-artifact@v4
        with:
          name: journaler-windows-latest
          path: dist/
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
